frappe.pages["scenario-story"].on_page_load = (wrapper) => {
	new ScenarioStory(wrapper);
};

class ScenarioStory {
	constructor(wrapper) {
		this.page = frappe.ui.make_app_page({
			parent: wrapper,
			title: __("Scenario Story"),
			single_column: true,
		});
		this.body = $('<div class="scenario-story">').appendTo(this.page.main);
		this.load();
	}

	async load() {
		const run_name = frappe.utils.get_url_arg("run");
		if (!run_name) {
			this.body.html(
				`<div class="alert alert-warning">${__("Select a Scenario Run first.")}</div>`
			);
			return;
		}
		const response = await frappe.call({
			method: "frappe_scenario.api.narrative.get_story",
			args: { run_name },
			freeze: true,
			freeze_message: __("Loading the business story…"),
		});
		this.render(response.message);
	}

	render(story) {
		this.page.set_title(story.run.title);
		this.body.empty();
		$(
			`<div class="mb-4"><h3>${frappe.utils.escape_html(
				story.run.company || story.run.title
			)}</h3>
			<p class="text-muted">${__(
				"A chronological explanation of the real ERPNext records generated by this scenario."
			)}</p></div>`
		).appendTo(this.body);
		if (!story.events.length) {
			this.body.append(
				`<div class="alert alert-info">${__(
					"This scenario has no narrative events."
				)}</div>`
			);
			return;
		}
		story.events.forEach((event) => {
			const card = $(`
				<div class="card mb-3">
					<div class="card-body">
						<div class="text-muted small">${frappe.datetime.str_to_user(
							event.event_date
						)} · ${frappe.utils.escape_html(event.event_type)}</div>
						<h4>${frappe.utils.escape_html(event.title)}</h4>
						<p>${frappe.utils.escape_html(event.summary || "")}</p>
						<button class="btn btn-sm btn-primary explain-record">${__("Explain this record")}</button>
						<a class="btn btn-sm btn-default ml-2" href="/app/${frappe.router.slug(
							event.reference_doctype
						)}/${encodeURIComponent(event.reference_name)}">${__(
				"Open ERPNext record"
			)}</a>
						<div class="explanation mt-3"></div>
					</div>
				</div>
			`).appendTo(this.body);
			card.find(".explain-record").on("click", () =>
				this.explain(story.run.name, event, card)
			);
		});
	}

	async explain(run_name, event, card) {
		const response = await frappe.call({
			method: "frappe_scenario.api.narrative.explain_record",
			args: {
				run_name,
				doctype: event.reference_doctype,
				name: event.reference_name,
			},
		});
		const explanation = response.message.event;
		card.find(".explanation").html(`
			<dl>
				<dt>${__("Why it exists")}</dt><dd>${frappe.utils.escape_html(explanation.why)}</dd>
				<dt>${__("Operational effect")}</dt><dd>${frappe.utils.escape_html(
			explanation.operational_effect
		)}</dd>
				<dt>${__("Ledger effect")}</dt><dd>${frappe.utils.escape_html(explanation.ledger_effect)}</dd>
				<dt>${__("Stock effect")}</dt><dd>${frappe.utils.escape_html(explanation.stock_effect)}</dd>
				<dt>${__("If cancelled or returned")}</dt><dd>${frappe.utils.escape_html(
			explanation.cancellation_consequence
		)}</dd>
			</dl>
		`);
	}
}
