# Copyright (c) 2026, Agathodaemon and contributors
# For license information, please see license.txt
"""Distribution and wholesale business archetype."""

from frappe_scenario.archetypes.base import Archetype, ItemFamily

FAMILIES = [
	ItemFamily(
		"bulk_goods",
		"Bulk Merchandise",
		"equipment",
		"Wholesale Goods",
		"Nos",
		(18, 650),
		(0.10, 0.22),
		(14, 60),
		3.5,
		3.5,
		True,
		(6, 80),
		("Commercial", "Standard", "Industrial", "Contract"),
	),
	ItemFamily(
		"trade_consumables",
		"Trade Consumables",
		"consumable",
		"Wholesale Consumables",
		"Box",
		(4, 90),
		(0.20, 0.36),
		(7, 30),
		2.5,
		3.0,
		True,
		(2, 30),
		("Bulk Pack", "Contract Pack", "Trade Pack", "Economy"),
	),
	ItemFamily(
		"replacement_parts",
		"Replacement Parts",
		"spare",
		"Wholesale Parts",
		"Nos",
		(8, 220),
		(0.28, 0.48),
		(10, 45),
		1.5,
		1.8,
		True,
		(1, 16),
		("Compatible", "Heavy Duty", "OEM Grade", "Universal"),
	),
	ItemFamily(
		"trade_services",
		"Trade Services",
		"service",
		"Wholesale Services",
		"Hour",
		(25, 180),
		(0.42, 0.62),
		(0, 0),
		0.5,
		0.8,
		False,
		(1, 12),
		("Delivery Coordination", "Product Training", "Installation", "Technical Support"),
	),
]

ARCHETYPE = Archetype(
	id="distribution_wholesale",
	title="Distribution and Wholesale",
	description="A regional wholesaler serving retailers and contract customers through repeat bulk trade.",
	default_country="United States",
	industry="Distribution",
	item_groups=["Wholesale Goods", "Wholesale Consumables", "Wholesale Parts", "Wholesale Services"],
	warehouses=[
		{"type": "main_store", "title": "Distribution Center"},
		{"type": "dispatch", "title": "Dispatch Warehouse"},
	],
	families=FAMILIES,
	customer_segments={"independent_retailer": 4, "regional_chain": 2, "contract_buyer": 3, "reseller": 2},
	payment_terms={"cash": 1, "net_30": 4, "net_60": 3, "net_90": 1},
	peak_months=[9, 10, 11],
	peak_multiplier=1.3,
	cash_sales_ratio=0.08,
	gross_margin_range=(0.10, 0.62),
	uoms=["Nos", "Box", "Pallet", "Hour"],
	supported_modules=("CRM", "Selling", "Buying", "Stock", "Accounts"),
	operational_ratios={"returns": 0.04, "customer_concentration": 0.45, "supplier_concentration": 0.35},
	learning_paths=("crm-parties", "buying", "selling", "stock", "payments", "returns"),
	validation_expectations=("balanced_books", "stock_integrity", "document_links", "customer_concentration"),
	required_capabilities=(
		"erpnext.commercial.crm",
		"erpnext.buying.purchase_invoices",
		"erpnext.selling.sales_invoices",
		"erpnext.accounts.customer_payments",
	),
	lifecycle_validated=True,
)
