# Copyright (c) 2026, Agathodaemon and contributors
# For license information, please see license.txt
"""Professional services business archetype."""

from frappe_scenario.archetypes.base import Archetype, ItemFamily

FAMILIES = [
	ItemFamily(
		"advisory",
		"Advisory Services",
		"service",
		"Advisory Services",
		"Hour",
		(45, 220),
		(0.45, 0.68),
		(0, 0),
		3,
		3,
		False,
		(4, 40),
		("Strategy", "Operations", "Finance", "Technology"),
	),
	ItemFamily(
		"implementation",
		"Implementation Services",
		"service",
		"Implementation Services",
		"Hour",
		(35, 180),
		(0.40, 0.62),
		(0, 0),
		3,
		3.5,
		False,
		(8, 80),
		("Configuration", "Migration", "Integration", "Rollout"),
	),
	ItemFamily(
		"managed_support",
		"Managed Support",
		"service",
		"Managed Services",
		"Month",
		(120, 900),
		(0.48, 0.70),
		(0, 0),
		2,
		2.5,
		False,
		(1, 12),
		("Essential", "Business", "Priority", "Enterprise"),
	),
	ItemFamily(
		"training",
		"Training Services",
		"service",
		"Training Services",
		"Day",
		(100, 700),
		(0.52, 0.72),
		(0, 0),
		1,
		1.2,
		False,
		(1, 5),
		("Foundation", "Practitioner", "Workshop", "Executive"),
	),
]

ARCHETYPE = Archetype(
	id="professional_services",
	title="Professional Services",
	description="A consultancy delivering advisory, implementation, managed support, and training engagements.",
	default_country="United States",
	industry="Professional Services",
	item_groups=["Advisory Services", "Implementation Services", "Managed Services", "Training Services"],
	warehouses=[{"type": "main_store", "title": "Non-Stock Operations"}],
	families=FAMILIES,
	customer_segments={"small_business": 2, "mid_market": 4, "enterprise": 2, "public_sector": 1},
	payment_terms={"cash": 1, "net_30": 5, "net_60": 2},
	peak_months=[1, 9, 10],
	peak_multiplier=1.2,
	cash_sales_ratio=0.05,
	gross_margin_range=(0.40, 0.72),
	uoms=["Hour", "Day", "Month"],
	supported_modules=("CRM", "Selling", "Accounts"),
	operational_ratios={"returns": 0.02, "customer_concentration": 0.35},
	learning_paths=("crm-parties", "selling", "payments", "reports-closing"),
	validation_expectations=("balanced_books", "document_links", "service_margin", "receivables_ageing"),
	required_capabilities=(
		"erpnext.commercial.crm",
		"erpnext.selling.sales_invoices",
		"erpnext.accounts.customer_payments",
	),
	lifecycle_validated=True,
)
