# Copyright (c) 2026, Agathodaemon and contributors
# For license information, please see license.txt
"""Retail business archetype."""

from frappe_scenario.archetypes.base import Archetype, ItemFamily

FAMILIES = [
	ItemFamily(
		"everyday_goods",
		"Everyday Goods",
		"equipment",
		"Retail Goods",
		"Nos",
		(5, 180),
		(0.22, 0.38),
		(7, 30),
		3.0,
		4.0,
		True,
		(1, 5),
		("Classic", "Everyday", "Compact", "Premium"),
	),
	ItemFamily(
		"seasonal_goods",
		"Seasonal Goods",
		"accessory",
		"Seasonal Merchandise",
		"Nos",
		(4, 140),
		(0.30, 0.48),
		(14, 45),
		1.5,
		2.5,
		True,
		(1, 4),
		("Summer", "Winter", "Holiday", "Limited"),
	),
	ItemFamily(
		"retail_consumables",
		"Retail Consumables",
		"consumable",
		"Retail Consumables",
		"Box",
		(1, 35),
		(0.32, 0.52),
		(5, 21),
		3.0,
		4.5,
		True,
		(1, 8),
		("Value Pack", "Family Pack", "Refill", "Daily"),
	),
	ItemFamily(
		"customer_services",
		"Customer Services",
		"service",
		"Retail Services",
		"Hour",
		(12, 80),
		(0.48, 0.68),
		(0, 0),
		0.4,
		0.7,
		False,
		(1, 3),
		("Assembly", "Home Delivery", "Setup", "Extended Support"),
	),
]

ARCHETYPE = Archetype(
	id="retail",
	title="Retail",
	description="A consumer retailer with frequent cash sales, replenishment, seasonal merchandise, and returns.",
	default_country="United States",
	industry="Retail",
	item_groups=["Retail Goods", "Seasonal Merchandise", "Retail Consumables", "Retail Services"],
	warehouses=[{"type": "main_store", "title": "Back Store"}, {"type": "showroom", "title": "Sales Floor"}],
	families=FAMILIES,
	customer_segments={"walk_in": 7, "loyalty_member": 3, "small_business": 1},
	payment_terms={"cash": 8, "net_30": 1},
	peak_months=[11, 12],
	peak_multiplier=1.55,
	cash_sales_ratio=0.72,
	gross_margin_range=(0.22, 0.68),
	uoms=["Nos", "Box", "Pack", "Hour"],
	supported_modules=("CRM", "Selling", "Buying", "Stock", "Accounts"),
	operational_ratios={"returns": 0.12, "customer_concentration": 0.05},
	learning_paths=("crm-parties", "buying", "selling", "stock", "payments", "returns"),
	validation_expectations=("balanced_books", "stock_integrity", "document_links", "cash_sales_mix"),
	required_capabilities=(
		"erpnext.buying.purchase_invoices",
		"erpnext.selling.sales_invoices",
		"erpnext.selling.returns",
	),
	lifecycle_validated=True,
)
